# Generated by Django 3.0.7 on 2020-06-20 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homologations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('project_name', models.CharField(max_length=128, verbose_name='Nome do projeto')),
                ('project_folder', models.CharField(blank=True, help_text='Caso queira que o diretório tenha um nome diferente do projeto git', max_length=32, null=True, verbose_name='Diretório do projeto')),
                ('docker_folder', models.CharField(blank=True, help_text='Nome do diretório onde fica o arquivo docker-composer, se for na raiz deixe em branco', max_length=32, null=True, verbose_name='Diretório do docker')),
                ('git_repository_url', models.CharField(help_text='git remote url ssh: git@(domínio):(usuário)/(projeto).git', max_length=255, verbose_name='URL Git')),
                ('container_name', models.CharField(help_text='Nome dado para o cotainer principal do docker', max_length=128, verbose_name='Nome do Container')),
                ('container_port', models.CharField(help_text='Número da porta dada para o cotainer principal do docker', max_length=128, verbose_name='Porta do Container')),
                ('settings_file', models.TextField(help_text='Configurações que serão copiadas para o .env', verbose_name='Configurações .env')),
                ('project_description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Homologação',
                'verbose_name_plural': 'Homologações',
            },
        ),
    ]
