# Generated by Django 3.0.7 on 2020-06-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homologations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyssh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_path', models.CharField(help_text='/home/(usuário)/.ssh/', max_length=128, verbose_name='Caminho para chave')),
                ('file_name', models.CharField(help_text='(arquivo).pub', max_length=32, verbose_name='Nome do arquivo')),
            ],
            options={
                'verbose_name': 'Chave SSH',
                'verbose_name_plural': 'Chaves SSH',
            },
        ),
    ]
