# Generated by Django 3.0.7 on 2020-06-21 02:52
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homologations', '0002_keyssh'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyssh',
            name='active',
            field=models.BooleanField(default=True, help_text='Arquivo está ativo', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='keyssh',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyssh',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
