# Generated by Django 3.0.7 on 2020-06-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homologations', '0004_auto_20200620_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homologations',
            name='container_name',
            field=models.CharField(blank=True, help_text='Nome dado para o cotainer principal do docker', max_length=128, null=True, verbose_name='Nome do Container'),
        ),
        migrations.AlterField(
            model_name='homologations',
            name='container_port',
            field=models.CharField(blank=True, help_text='Número da porta dada para o cotainer principal do docker', max_length=128, null=True, verbose_name='Porta do Container'),
        ),
        migrations.AlterField(
            model_name='homologations',
            name='settings_file',
            field=models.TextField(blank=True, help_text='Configurações que serão copiadas para o .env', null=True, verbose_name='Configurações .env'),
        ),
    ]
